### ISSUE TITLE
Not all strings of mseide and msei18n were marked for translation

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#2]
Some strings from mseide and msei18n were not marked for translation by tstringcontainer.
For example, hints from Component Palette, About dialog, etc.
Needs to do full review of code and to mark strings for translation.
Martin started to do this job, but did not finish.

Current translation process:
http://svnweb.mageia.org/packages/cauldron/mseide-msegui/current/
SRPM: http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/SRPMS/core/release/

**Comment by fredvs** [comment]
Fixed in commit 3929f5c.

**Comment by glixx** [comment]
Not fixed. Not localized strings are still in code, but should be in tstringcontainer to be available to translate.

**Comment by fredvs** [comment]
Is it fixed?

**Comment by glixx** [comment]
No. Needs to review all code and move strings from code into tstringcontainer.

**Comment by fredvs** [comment]
Oooops.

**Comment by glixx** [comment]
msei18n smaller to do this task faster.

**Comment by glixx** [comment]
Localization "About" dialog:
```
procedure tmainfo.aboutexe(const sender: TObject);
begin
 showmessage('MSEgui version: '+mseguiversiontext+lineend+
         'MSEi18n version: ' + msei18nversiontext,'About MSEi18n');
end;
```
```
procedure tmainfo.aboutonexecute(const sender: TObject);
begin
 showmessage('MSEide version: '+versiontext+c_linefeed+
             'MSEgui version: '+mseguiversiontext+c_linefeed+
             'Host: '+ platformtext+ c_linefeed+
             c_linefeed+
             copyrighttext+c_linefeed+
             'by Martin Schreiber'
             ,actionsmo.c[ord(ac_about)]+' MSEide');
end;
```

For the easiest localization we can use constants:
```
'%s version'
'Host'
'About %s'
```

**Comment by glixx** [comment]
Localization of "About" dialog: https://github.com/mse-org/mseide-msegui/commit/63609f5901820c40ff709595a34a6ffba75d880c

**Comment by fredvs** [comment]
Yes, this is detail, maybe in future reease.
