### ISSUE TITLE
Problems with " for txt import

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#47]
Extra space before or after "
![Screenshot_20190405_053105](https://user-images.githubusercontent.com/2681872/55605432-35674680-577d-11e9-9ac1-f45ed5399cc1.png)

**Comment by glixx** [comment]
![Screenshot_20190405_053830](https://user-images.githubusercontent.com/2681872/55605712-6c8a2780-577e-11e9-8378-839083a514c5.png)

**Comment by glixx** [comment]
msei18 has 41 problematic strings.

**Comment by fredvs** [comment]
There is problem indeed with " because it is recognized as separator.
The workaround used was to remove all the " but of course it is not perfect.
I did forget this.
I will try a other workaround.

**Comment by fredvs** [comment]
Fixed in last commit.

**Comment by glixx** [comment]
Same issue for import txt file

**Comment by fredvs** [comment]
> Same issue for import txt file

Are you talking about `txt` files created by `msei18n` and for use to translation with Google-translate?
This should be considered as "Work in progress".
When I have more free time I will jump back into it to find better syntax  for Google translate.

**Comment by glixx** [comment]
Problem is not with syntax, but loosing " after import.

**Comment by fredvs** [comment]
> Problem is not with syntax, but loosing " after import.

Yes, custom `txt` is not perfect yet.

Please let's concentrate now about `po`, `csv` and `trd` files.
Normally import/export with `po`, `csv` and `trd` should give same result.

`txt` file is different and will be more "random" because all must be checked after Google work.
It will be a kind of automatic translator.

**Comment by glixx** [comment]
It loses " even of to import txt file without translations.

**Comment by glixx** [comment]
It loses " even if to import txt file without translations.

**Comment by fredvs** [comment]
> It loses " even if to import txt file without translations.

https://github.com/mse-org/mseide-msegui/issues/47#issuecomment-480802674

**Comment by fredvs** [comment]
Ha, ok, I see, I work on it.

**Comment by fredvs** [comment]
Ok, should be fixed in last commit.

**Comment by glixx** [comment]
Not fixed.

open mseide en project;
export into txt;
(do not need to translate txt file)
import from txt;

**Comment by fredvs** [comment]
> Not fixed.
> 
> open mseide en project;
> export into txt;
> (do not need to translate txt file)
> import from txt;


Do you have problem importing po or csv ?

Did you read this ( 3x that I noted:) #47 (comment)

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/47#issuecomment-480802674

**Comment by glixx** [comment]
> Do you have problem importing po or csv ?

txt

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/47#issuecomment-480802674
